### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by elias-knodel** [lazybytez/jojo-discord-bot#70]
## Describe the solution you'd like:

* [x] Add correct Badge links
* [x] Add CodeCov Badge 
* [x] Add Go Docs Reference Badge
* [x] Fix `general-template` links still in readme
* [x] Maybe remove some useless badges because when we add two it should be bloated
* [x] Maybe add some test and lint helping (or not, I mean unlimited workflow runs right?)

**Comment by pascal-zarrad** [comment]
@elias-knodel Regarding removal of badges; I suggest to remove the repo size and last commit badges.

**Comment by elias-knodel** [comment]
Helpful resource: https://golangci-lint.run/usage/install/#local-installation
