### ISSUE TITLE
Commands don't work in Direct Messages

### ISSUE THREAD

**Issue by elias-knodel** [lazybytez/jojo-discord-bot#87]
## Describe the bug:

The Bot does not work in direct messages (DM).

## To Reproduce:

1. Start Bot
2. Go into Bot Direct Messages
3. Execute `/ping`
4. Get Error

## Expected behavior:

You should be able to execute non guild dependent commands like ping, stats etc. in DM's.

## Screenshots:

```json
{"level":"warn","component":"Ping Pong","time":"2022-10-01T16:35:17+02:00","message":"Missing guild with ID \"\" in database!"}
{"level":"warn","component":"Ping Pong","time":"2022-10-01T16:35:17+02:00","message":"Missing guild with ID \"\" in database!"}
```

**Comment by pascal-zarrad** [comment]
This is right now intentional behaviour and by design.
We will have to find a clean way to handle global commands.
